### ISSUE TITLE
Unable to find snps-excluded.txt file

### ISSUE THREAD

**Issue by tlawler2** [genepi/imputationserver2#27]
Hello,

I am attempting to use the server now that it has finished updates. In my recent attempt, my job failed during the quality control process (expected due to strand flips, allele switches), but I was unable to locate the snps-excluded.txt file. I need this file in order to correct the aberrant SNPs. Is anyone else having this problem? I think that the file was not created. Thank you to anyone who can help.

**Comment by seppinho** [comment]
We have just deployed a new version. You should now see the QC statistics. Thanks for reporting this issue!

**Comment by tlawler2** [comment]
It works! Thanks for your attention to this issue.

-Tom


________________________________

**Comment by seppinho** [comment]
Great! If you have scripts for fixing the issues (or using the W. Rayner tool), please let us know so we can share it with the community on our help page.
