### ISSUE TITLE
Imputation failed for chromosome 9

### ISSUE THREAD

**Issue by ryshi06** [genepi/imputationserver2#33]
I’m currently working on imputation for a merged cohort, but I’ve encountered repeated failures specifically with chromosome 9, and the cause isn’t clear. I’ve attached a text file with the relevant statistics and failure details. The error messages include “Pipeline execution failed” and “Imputation Job failed,” but don’t provide further clarification.
 
Here’s a summary of the workflow I followed to prepare the files for imputation:
 
1. I downloaded the individual cohort PLINK files from the public website.
2. After ensuring all cohorts were aligned to build 19, I ran imputation jobs for each cohort separately (with no issues at this stage), as they were genotyped using different arrays.
3. I merged the post-imputation VCF files from each cohort and converted them into PLINK format.
4. I conducted a pseudo-case-control GWAS on the normal population from the individual cohorts, excluding significant variants (p-value < 1E-05) to control for potential batch effects from the genotyping arrays.
5. Finally, I ran the HRC pre-imputation tool again on the merged cohort and submitted the imputation jobs.
 
Given this process, I didn’t observe any potential errors, so I’m unsure why chromosome 9 keeps failing. Could you help me troubleshoot this issue and possibly provide some explanations or solutions?
 
Thank you in advance for your help!

**Comment by seppinho** [comment]
Thanks! I think this is not related to the actual pipeline code but rather some edge case with your input data. We’ll look into that. Let’s follow up via email. See MIS website for my contact details
